# // TODO: Implementar el docker-compose
version: '3.8'

services:
  libreria-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/libreria_db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - EXTERNAL_API_BOOKS_URL=https://my-json-server.typicode.com/Gabriel-Arriola-UTN/libros/books
    volumes:
      - h2_data:/data
    networks:
      - libreria-network
    restart: unless-stopped

networks:
  libreria-network:
    driver: bridge

volumes:
  h2_data:
    driver: local